# [START container_nginxapp_service_load_balancer]
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-server
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP 
    port: 80
  selector:
    app: nginx
# [END container_nginxapp_service_load_balancer]
