# [START container_nginxapp_deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-server
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-web
        image: gcr.io/srebootcamp/my-web-server
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
# [END container_nginxapp_deployment]  
